/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneoRouteImport } from './routes/torneo'
import { Route as ReducidoRouteImport } from './routes/reducido'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as AmistosoRouteImport } from './routes/amistoso'
import { Route as IndexRouteImport } from './routes/index'

const TorneoRoute = TorneoRouteImport.update({
  id: '/torneo',
  path: '/torneo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReducidoRoute = ReducidoRouteImport.update({
  id: '/reducido',
  path: '/reducido',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const AmistosoRoute = AmistosoRouteImport.update({
  id: '/amistoso',
  path: '/amistoso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amistoso': typeof AmistosoRoute
  '/equipos': typeof EquiposRoute
  '/reducido': typeof ReducidoRoute
  '/torneo': typeof TorneoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amistoso': typeof AmistosoRoute
  '/equipos': typeof EquiposRoute
  '/reducido': typeof ReducidoRoute
  '/torneo': typeof TorneoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amistoso': typeof AmistosoRoute
  '/equipos': typeof EquiposRoute
  '/reducido': typeof ReducidoRoute
  '/torneo': typeof TorneoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/amistoso' | '/equipos' | '/reducido' | '/torneo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amistoso' | '/equipos' | '/reducido' | '/torneo'
  id: '__root__' | '/' | '/amistoso' | '/equipos' | '/reducido' | '/torneo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmistosoRoute: typeof AmistosoRoute
  EquiposRoute: typeof EquiposRoute
  ReducidoRoute: typeof ReducidoRoute
  TorneoRoute: typeof TorneoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneo': {
      id: '/torneo'
      path: '/torneo'
      fullPath: '/torneo'
      preLoaderRoute: typeof TorneoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reducido': {
      id: '/reducido'
      path: '/reducido'
      fullPath: '/reducido'
      preLoaderRoute: typeof ReducidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amistoso': {
      id: '/amistoso'
      path: '/amistoso'
      fullPath: '/amistoso'
      preLoaderRoute: typeof AmistosoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmistosoRoute: AmistosoRoute,
  EquiposRoute: EquiposRoute,
  ReducidoRoute: ReducidoRoute,
  TorneoRoute: TorneoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
