/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneoRouteImport } from './routes/torneo'
import { Route as ReducidoRouteImport } from './routes/reducido'
import { Route as LogrosRouteImport } from './routes/logros'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as CarreraRouteImport } from './routes/carrera'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmistosoRouteImport } from './routes/amistoso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquiposIdRouteImport } from './routes/equipos.$id'

const TorneoRoute = TorneoRouteImport.update({
  id: '/torneo',
  path: '/torneo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReducidoRoute = ReducidoRouteImport.update({
  id: '/reducido',
  path: '/reducido',
  getParentRoute: () => rootRouteImport,
} as any)
const LogrosRoute = LogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreraRoute = CarreraRouteImport.update({
  id: '/carrera',
  path: '/carrera',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmistosoRoute = AmistosoRouteImport.update({
  id: '/amistoso',
  path: '/amistoso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposIdRoute = EquiposIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EquiposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amistoso': typeof AmistosoRoute
  '/auth': typeof AuthRoute
  '/carrera': typeof CarreraRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/estadisticas': typeof EstadisticasRoute
  '/logros': typeof LogrosRoute
  '/reducido': typeof ReducidoRoute
  '/torneo': typeof TorneoRoute
  '/equipos/$id': typeof EquiposIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amistoso': typeof AmistosoRoute
  '/auth': typeof AuthRoute
  '/carrera': typeof CarreraRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/estadisticas': typeof EstadisticasRoute
  '/logros': typeof LogrosRoute
  '/reducido': typeof ReducidoRoute
  '/torneo': typeof TorneoRoute
  '/equipos/$id': typeof EquiposIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amistoso': typeof AmistosoRoute
  '/auth': typeof AuthRoute
  '/carrera': typeof CarreraRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/estadisticas': typeof EstadisticasRoute
  '/logros': typeof LogrosRoute
  '/reducido': typeof ReducidoRoute
  '/torneo': typeof TorneoRoute
  '/equipos/$id': typeof EquiposIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/amistoso'
    | '/auth'
    | '/carrera'
    | '/equipos'
    | '/estadisticas'
    | '/logros'
    | '/reducido'
    | '/torneo'
    | '/equipos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/amistoso'
    | '/auth'
    | '/carrera'
    | '/equipos'
    | '/estadisticas'
    | '/logros'
    | '/reducido'
    | '/torneo'
    | '/equipos/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/amistoso'
    | '/auth'
    | '/carrera'
    | '/equipos'
    | '/estadisticas'
    | '/logros'
    | '/reducido'
    | '/torneo'
    | '/equipos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AmistosoRoute: typeof AmistosoRoute
  AuthRoute: typeof AuthRoute
  CarreraRoute: typeof CarreraRoute
  EquiposRoute: typeof EquiposRouteWithChildren
  EstadisticasRoute: typeof EstadisticasRoute
  LogrosRoute: typeof LogrosRoute
  ReducidoRoute: typeof ReducidoRoute
  TorneoRoute: typeof TorneoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneo': {
      id: '/torneo'
      path: '/torneo'
      fullPath: '/torneo'
      preLoaderRoute: typeof TorneoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reducido': {
      id: '/reducido'
      path: '/reducido'
      fullPath: '/reducido'
      preLoaderRoute: typeof ReducidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logros': {
      id: '/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof LogrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrera': {
      id: '/carrera'
      path: '/carrera'
      fullPath: '/carrera'
      preLoaderRoute: typeof CarreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amistoso': {
      id: '/amistoso'
      path: '/amistoso'
      fullPath: '/amistoso'
      preLoaderRoute: typeof AmistosoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/$id': {
      id: '/equipos/$id'
      path: '/$id'
      fullPath: '/equipos/$id'
      preLoaderRoute: typeof EquiposIdRouteImport
      parentRoute: typeof EquiposRoute
    }
  }
}

interface EquiposRouteChildren {
  EquiposIdRoute: typeof EquiposIdRoute
}

const EquiposRouteChildren: EquiposRouteChildren = {
  EquiposIdRoute: EquiposIdRoute,
}

const EquiposRouteWithChildren =
  EquiposRoute._addFileChildren(EquiposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AmistosoRoute: AmistosoRoute,
  AuthRoute: AuthRoute,
  CarreraRoute: CarreraRoute,
  EquiposRoute: EquiposRouteWithChildren,
  EstadisticasRoute: EstadisticasRoute,
  LogrosRoute: LogrosRoute,
  ReducidoRoute: ReducidoRoute,
  TorneoRoute: TorneoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
