-- Unifica todos los clubes en public.teams para que admin y el juego usen la misma fuente de verdad.
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS division text NOT NULL DEFAULT 'primera_nacional';
UPDATE public.teams SET division = 'primera_nacional' WHERE division IS NULL OR division = '';
GRANT SELECT ON public.teams TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.teams TO authenticated;
DROP POLICY IF EXISTS "teams readable" ON public.teams;
CREATE POLICY "teams readable" ON public.teams FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "admins insert teams" ON public.teams;
CREATE POLICY "admins insert teams" ON public.teams FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'admin'));
DROP POLICY IF EXISTS "admins update teams" ON public.teams;
CREATE POLICY "admins update teams" ON public.teams FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
DROP POLICY IF EXISTS "admins delete teams" ON public.teams;
CREATE POLICY "admins delete teams" ON public.teams FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'));
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.teams; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

INSERT INTO public.teams (id,name,short,city,zone,division,primary_color,secondary_color,stripe,speed,jump,power,defense,logo_url,rivals,goal_audio_urls,hinchada_urls,narrators,flag_urls,full_name,founded_year,province,nickname,rival_id,primera_seasons)
VALUES
('aldosivi', 'Aldosivi', 'ALD', 'Mar del Plata', 'A', 'primera_division', '#f7d117', '#1a8a3e', 'horizontal', 81, 81, 79, 82, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('argentinosjuniors', 'Argentinos Juniors', 'ARG', 'La Paternal, CABA', 'A', 'primera_division', '#e6222a', '#ffffff', 'sash', 81, 86, 86, 83, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('atleticotucuman', 'Atlético Tucumán', 'ATL', 'San Miguel de Tucumán', 'A', 'primera_division', '#7ec6e8', '#ffffff', 'vertical', 79, 80, 83, 86, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('banfield', 'Banfield', 'BAN', 'Banfield', 'A', 'primera_division', '#1a8a3e', '#ffffff', 'sash', 79, 80, 78, 85, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('barracascentral', 'Barracas Central', 'BAR', 'Barracas, CABA', 'A', 'primera_division', '#c1121f', '#111111', 'horizontal', 82, 79, 79, 84, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('belgrano', 'Belgrano', 'BEL', 'Córdoba', 'A', 'primera_division', '#7ec6e8', '#ffffff', 'vertical', 81, 85, 79, 82, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('bocajuniors', 'Boca Juniors', 'BOC', 'La Boca, CABA', 'A', 'primera_division', '#0a2b5c', '#f7d117', 'horizontal', 86, 82, 80, 84, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('centralcordoba', 'Central Córdoba (SdE)', 'CEN', 'Santiago del Estero', 'A', 'primera_division', '#111111', '#ffffff', 'vertical', 84, 85, 82, 83, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('defensayjusticia', 'Defensa y Justicia', 'DEF', 'Florencio Varela', 'A', 'primera_division', '#1a8a3e', '#c1121f', 'horizontal', 79, 81, 84, 80, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivoriestra', 'Deportivo Riestra', 'DEP', 'Villa Soldati, CABA', 'A', 'primera_division', '#111111', '#c1121f', 'sash', 81, 84, 79, 83, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('estudiantesdelaplata', 'Estudiantes de La Plata', 'EST', 'La Plata', 'A', 'primera_division', '#c1121f', '#ffffff', 'vertical', 84, 84, 85, 80, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('estudiantesderiocuarto', 'Estudiantes de Río Cuarto', 'ERC', 'Río Cuarto', 'A', 'primera_division', '#c1121f', '#ffffff', 'solid', 86, 79, 84, 83, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('gimnasiayesgrimalaplata', 'Gimnasia y Esgrima La Plata', 'GEP', 'La Plata', 'A', 'primera_division', '#0a3d91', '#ffffff', 'vertical', 86, 79, 83, 85, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('gimnasiayesgrimademendoza', 'Gimnasia y Esgrima de Mendoza', 'GEM', 'Mendoza', 'A', 'primera_division', '#0a3d91', '#ffffff', 'vertical', 83, 84, 86, 85, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('huracan', 'Huracán', 'HUR', 'Parque Patricios, CABA', 'A', 'primera_division', '#ffffff', '#c1121f', 'solid', 85, 83, 80, 83, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('independiente', 'Independiente', 'IND', 'Avellaneda', 'A', 'primera_division', '#c1121f', '#ffffff', 'solid', 84, 82, 79, 81, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('independienterivadavia', 'Independiente Rivadavia', 'IND', 'Mendoza', 'A', 'primera_division', '#1a8a3e', '#ffffff', 'solid', 81, 78, 79, 78, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('instituto', 'Instituto', 'INS', 'Córdoba', 'A', 'primera_division', '#c1121f', '#ffffff', 'vertical', 78, 79, 79, 78, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('lanus', 'Lanús', 'LAN', 'Lanús', 'A', 'primera_division', '#7a1f3d', '#ffffff', 'solid', 81, 85, 81, 86, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('newellsoldboys', 'Newell''s Old Boys', 'NOB', 'Rosario', 'A', 'primera_division', '#c1121f', '#111111', 'vertical', 85, 81, 78, 85, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('platense', 'Platense', 'PLA', 'Vicente López', 'A', 'primera_division', '#7a1f3d', '#e8d9b0', 'horizontal', 78, 85, 84, 79, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('racingclub', 'Racing Club', 'RAC', 'Avellaneda', 'A', 'primera_division', '#7ec6e8', '#ffffff', 'vertical', 80, 86, 83, 81, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('riverplate', 'River Plate', 'RIV', 'Núñez, CABA', 'A', 'primera_division', '#ffffff', '#c1121f', 'sash', 81, 81, 78, 79, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('rosariocentral', 'Rosario Central', 'ROS', 'Rosario', 'A', 'primera_division', '#0a3d91', '#f7d117', 'vertical', 80, 81, 83, 79, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sanlorenzo', 'San Lorenzo', 'SAN', 'Boedo, CABA', 'A', 'primera_division', '#0a3d91', '#c1121f', 'vertical', 86, 85, 85, 83, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sarmientodejunin', 'Sarmiento de Junín', 'SAR', 'Junín', 'A', 'primera_division', '#1a8a3e', '#ffffff', 'solid', 83, 84, 83, 82, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('talleresdecordoba', 'Talleres de Córdoba', 'TAL', 'Córdoba', 'A', 'primera_division', '#0a3d91', '#ffffff', 'sash', 78, 85, 85, 84, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('tigre', 'Tigre', 'TIG', 'Victoria, Tigre', 'A', 'primera_division', '#0a3d91', '#7a1f3d', 'vertical', 78, 83, 81, 84, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('uniondesantafe', 'Unión de Santa Fe', 'USF', 'Santa Fe', 'A', 'primera_division', '#c1121f', '#ffffff', 'solid', 80, 85, 82, 81, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('velezsarsfield', 'Vélez Sarsfield', 'VÉL', 'Villa Luro, CABA', 'A', 'primera_division', '#ffffff', '#0a3d91', 'sash', 86, 79, 78, 85, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('agropecuario-pb', 'Agropecuario', 'AGR', 'Carlos Casares', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 70, 70, 66, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('argentinodemerlo', 'Argentino de Merlo', 'ARG', 'Merlo', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 68, 70, 67, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('argentinodequilmes', 'Argentino de Quilmes', 'ARG', 'Quilmes', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 69, 67, 70, 72, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('arsenal', 'Arsenal', 'ARS', 'Sarandí', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 70, 71, 64, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('browndeadrogue', 'Brown de Adrogué', 'BRO', 'Adrogué', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 69, 65, 64, 71, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('canuelas', 'Cañuelas', 'CAÑ', 'Cañuelas', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 66, 65, 69, 69, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('colegiales-pb', 'Colegiales', 'COL', 'Munro', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 67, 68, 64, 66, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('comunicaciones', 'Comunicaciones', 'COM', 'Villa Lynch', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 66, 70, 66, 68, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('defensoresdebelgrano', 'Defensores de Belgrano', 'DEF', 'La Paternal, CABA', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 65, 71, 68, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('defensoresunidos', 'Defensores Unidos (CADU)', 'DEF', 'Zárate', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 68, 71, 71, 68, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivoarmenio', 'Deportivo Armenio', 'DEP', 'Ing. Maschwitz', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 66, 65, 65, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivocamioneros', 'Deportivo Camioneros', 'DEP', 'El Palomar', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 69, 68, 72, 71, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivolaferrere', 'Deportivo Laferrere', 'DEP', 'La Matanza', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 67, 71, 70, 71, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivomerlo', 'Deportivo Merlo', 'DEP', 'Merlo', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 72, 64, 64, 66, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('excursionistas', 'Excursionistas', 'EXC', 'Belgrano, CABA', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 66, 70, 65, 72, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('flandria', 'Flandria', 'FLA', 'Jáuregui, Luján', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 64, 68, 64, 71, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('liniers', 'Liniers', 'LIN', 'Liniers, Bahía Blanca', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 70, 67, 67, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('losandes-pb', 'Los Andes', 'LOS', 'Lomas de Zamora', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 69, 70, 67, 69, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('midgland', 'Midgland', 'MID', 'San Miguel', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 72, 65, 68, 68, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sanmartindeburzaco', 'San Martín de Burzaco', 'SAN', 'Burzaco', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 66, 72, 68, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sportivoitaliano', 'Sportivo Italiano', 'SPO', 'Villa Dominico', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 68, 67, 72, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('uaiurquiza', 'UAI Urquiza', 'UAI', 'Villa Lynch', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 71, 64, 70, 68, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('villadalmine', 'Villa Dálmine', 'VIL', 'Campana', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 72, 68, 72, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('villasancarlos', 'Villa San Carlos', 'VIL', 'Berisso', 'A', 'primera_b', '#3a4658', '#c7d0dc', 'solid', 67, 70, 72, 72, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('argentinoderosario', 'Argentino de Rosario', 'ARG', 'Rosario', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 66, 61, 60, 63, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('atlas', 'Atlas', 'ATL', 'Villa Devoto, CABA', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 61, 60, 63, 63, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('berazategui', 'Berazategui', 'BER', 'Berazategui', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 66, 63, 60, 60, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('centralballester', 'Central Ballester', 'CEN', 'Villa Ballester', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 66, 62, 59, 60, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('centralcordoba2', 'Central Córdoba (Rosario)', 'CEN', 'Rosario', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 61, 64, 60, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('centroespanol', 'Centro Español', 'CEN', 'Villa Sarmiento', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 65, 65, 61, 60, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('claypole', 'Claypole', 'CLA', 'Claypole', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 62, 64, 62, 60, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('defensoresdecambaceres', 'Defensores de Cambaceres', 'DEF', 'Ensenada', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 59, 59, 65, 63, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivoespanol', 'Deportivo Español', 'DEP', 'Bajo Flores, CABA', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 62, 58, 66, 66, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivoparaguayo', 'Deportivo Paraguayo', 'DEP', 'Ciudadela', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 60, 65, 61, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('elporvenir', 'El Porvenir', 'EL', 'Gerli', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 65, 63, 59, 59, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('estrelladelsur', 'Estrella del Sur', 'EST', 'Barracas, CABA', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 60, 66, 61, 66, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('generallamadrid', 'General Lamadrid', 'GEN', 'Villa Lynch', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 64, 60, 66, 62, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('jjurquiza', 'J.J. Urquiza', 'J.J', 'Villa Lynch', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 66, 64, 64, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('juventudunida', 'Juventud Unida', 'JUV', 'San Miguel', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 61, 59, 59, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('leandronalem', 'Leandro N. Alem', 'LNA', 'Castelar', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 66, 58, 58, 63, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('lugano', 'Lugano', 'LUG', 'Villa Lugano, CABA', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 61, 61, 61, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('mercedes', 'Mercedes', 'MER', 'Mercedes', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 64, 64, 58, 60, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('muniz', 'Muñiz', 'MUÑ', 'Muñiz', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 60, 58, 58, 63, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('puertonuevo', 'Puerto Nuevo', 'PUE', 'La Boca, CABA', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 59, 63, 65, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('realpilar', 'Real Pilar', 'REA', 'Pilar', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 58, 66, 63, 58, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sacachispas', 'Sacachispas', 'SAC', 'Villa Soldati, CABA', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 66, 58, 66, 59, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sportivobarracas', 'Sportivo Barracas', 'SPO', 'Barracas, CABA', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 66, 59, 59, 62, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('victorianoarenas', 'Victoriano Arenas', 'VIC', 'Lanús', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 61, 63, 63, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('yupanqui', 'Yupanqui', 'YUP', 'Parque Chas, CABA', 'A', 'primera_c', '#37424f', '#b9c3cf', 'solid', 59, 64, 62, 61, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('9dejulio', '9 de Julio (Rafaela)', '9', 'Rafaela', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 64, 65, 65, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('alvarado', 'Alvarado (Mar del Plata)', 'ALV', 'Mar del Plata', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 65, 69, 66, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('atenas', 'Atenas (Río Cuarto)', 'ATE', 'Río Cuarto', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 69, 69, 71, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('atleticoclubsanmartin', 'Atlético Club San Martín (Mendoza)', 'ACM', 'Mendoza', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 70, 71, 71, 69, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('bartolomemitre', 'Bartolomé Mitre (Posadas)', 'BAR', 'Posadas', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 66, 70, 66, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('bocaunidos', 'Boca Unidos (Corrientes)', 'BOC', 'Corrientes', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 72, 68, 64, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('cipolletti', 'Cipolletti', 'CIP', 'Cipolletti', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 64, 66, 67, 71, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('circulodeportivo', 'Círculo Deportivo (Otamendi)', 'CÍR', 'Otamendi', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 72, 67, 69, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('costabrava', 'Costa Brava (General Pico)', 'COS', 'General Pico', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 64, 69, 66, 71, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('defensores', 'Defensores (Puerto Vilelas)', 'DEF', 'Puerto Vilelas', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 65, 69, 69, 72, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('defensoresdebelgrano2', 'Defensores de Belgrano (Villa Ramallo)', 'DEF', 'Villa Ramallo', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 70, 72, 65, 68, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivoargentino', 'Deportivo Argentino (Monte Maíz)', 'DEP', 'Monte Maíz', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 71, 66, 72, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('deportivorincon', 'Deportivo Rincón (Rincón de los Sauces)', 'DEP', 'Rincón de los Sauces', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 68, 70, 65, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('douglashaig', 'Douglas Haig (Pergamino)', 'DOU', 'Pergamino', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 70, 65, 69, 66, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('ellinqueno', 'El Linqueño (Lincoln)', 'EL', 'Lincoln', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 71, 69, 68, 66, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('escobarfutbolclub', 'Escobar Fútbol Club', 'EFC', 'Escobar Fútbol Club', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 64, 64, 68, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('fadep', 'FADEP (Fundación Amigos por el Deporte)', 'FAD', 'Fundación Amigos por el Deporte', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 68, 69, 71, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('germinal', 'Germinal (Rawson)', 'GER', 'Rawson', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 65, 68, 70, 71, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('gimnasiayesgrima', 'Gimnasia y Esgrima (Chivilcoy)', 'GIM', 'Chivilcoy', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 72, 64, 65, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('gimnasiayesgrima2', 'Gimnasia y Esgrima (Concepción del Uruguay)', 'GIM', 'Concepción del Uruguay', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 64, 65, 70, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('guillermobrown', 'Guillermo Brown (Puerto Madryn)', 'GUI', 'Puerto Madryn', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 70, 64, 69, 69, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('huracanlasheras', 'Huracán Las Heras', 'HUR', 'Huracán Las Heras', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 72, 66, 72, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('independiente2', 'Independiente (Chivilcoy)', 'IND', 'Chivilcoy', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 69, 66, 67, 66, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('juventudantoniana', 'Juventud Antoniana (Salta)', 'JUV', 'Salta', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 70, 67, 66, 69, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('juventudunidauniversitario', 'Juventud Unida Universitario (San Luis)', 'JUU', 'San Luis', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 69, 70, 65, 65, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('kimberley', 'Kimberley (Mar del Plata)', 'KIM', 'Mar del Plata', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 65, 72, 69, 69, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('olimpo', 'Olimpo (Bahía Blanca)', 'OLI', 'Bahía Blanca', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 71, 69, 64, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sanmartin', 'San Martín (Formosa)', 'SAN', 'Formosa', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 68, 64, 71, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('santamarina', 'Santamarina (Tandil)', 'SAN', 'Tandil', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 68, 64, 66, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sarmiento', 'Sarmiento (La Banda)', 'SAR', 'La Banda', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 68, 72, 66, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sarmiento2', 'Sarmiento (Resistencia)', 'SAR', 'Resistencia', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 64, 71, 65, 67, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('soldeamerica', 'Sol de América (Formosa)', 'SOL', 'Formosa', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 65, 66, 67, 66, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('soldemayo', 'Sol de Mayo (Viedma)', 'SOL', 'Viedma', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 71, 72, 70, 72, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sportivoatleticoclub', 'Sportivo Atlético Club (Las Parejas)', 'SAC', 'Las Parejas', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 68, 70, 69, 68, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('sportivobelgrano', 'Sportivo Belgrano (San Francisco)', 'SPO', 'San Francisco', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 71, 67, 70, 70, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('tucumancentral', 'Tucumán Central', 'TUC', 'Tucumán Central', 'B', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 64, 64, 67, 64, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL),
('villamitre', 'Villa Mitre (Bahía Blanca)', 'VIL', 'Bahía Blanca', 'A', 'federal_a', '#2f3b4c', '#a9c6da', 'solid', 64, 71, 64, 69, NULL, '{}', '{}', '{}', '[]'::jsonb, '{}', NULL, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET division = EXCLUDED.division;
